Set device wallpaper based on theme
jkuester/unlauncher pull request #112
Opened 2022-05-29 12:08 UTC by hayribakici

Changes wallpaper background based on theme background, see #54  

TODO:
[ ] check if app is default launcher
[ ] ask user if device wallpaper should be changed as well
[ ] check if wallpaper color equals theme background color (so far, the wallpaper is always changing on app startup)
[x] change wallpaper color when user changes theme

2022-07-24 11:08 UTC, hayribakici commented
Setting back to draft, found a bug in the `CustomizeAppDrawerFragment` while switching default launchers.

2022-08-09 02:52 UTC, jkuester requested changes
Awesome work @hayribakici!  I have left a few comments/questions inline, but otherwise this is good to go!  

I know that it has taken me too long to look at this, so if you do not have the time to look at the comments, that is totally understandable. I can work on addressing them myself if needed.

Ultimately, I think this is a great feature! I think it makes sense to keep the behavior pretty much as you have it for this PR, but in the future, (maybe the next major version bump) it seems like it might make sense to enable this behavior by default (e.g. the setting the wallpaper happens automatically when Unlauncher is the default home app unless the user opts out of it in the Unlauncher settings).  I feel like most folks would want the wallpaper set.  But that is a challenge for another time. It seems appropriate to release the opt-in functionality first and get a good idea of how things work....

2022-08-09 02:52 UTC, jkuester commented on app/src/main/java/com/sduduzog/slimlauncher/MainActivity.kt
> +            if (!it.setThemeWallpaper && getUserSelectedThemeRes() == resid) {
Okay, I might be missing something here, but why do we need `&& getUserSelectedThemeRes() == resid`?  

Based on the implementation of `setTheme` below should this check always be true?

2022-08-09 02:52 UTC, jkuester commented on app/src/main/java/com/sduduzog/slimlauncher/MainActivity.kt
> +    @Throws(IOException::class)
I see this gets thrown by the `windowManager.setBitmap`. Do you see any reason why we should not just wrap that call in a try-catch and log the error instead of letting it propagate? I just down see any reason why a failure to set the background should affect the rest of the app (or even just block any part of the set-theme process)...

2022-08-09 02:52 UTC, jkuester commented on app/src/main/java/com/sduduzog/slimlauncher/ui/options/CustomizeAppDrawerFragment.kt
> +        setupKeyboardSwitch(unlauncherAppsRepo)
:heart:

2022-08-09 02:52 UTC, jkuester commented on app/src/main/java/com/sduduzog/slimlauncher/ui/options/CustomizeAppDrawerFragment.kt
> +    private fun setupKeyboardSwitch(appsRepo: UnlauncherAppsRepository) {
Minor, but do not really need to pass `appsRepo` in here since this method can just call `getUnlauncherDataSource().unlauncherAppsRepo` directly.

Same goes for the `setupAutomaticDeviceWallpaperSwitch` below.

2022-08-09 02:52 UTC, jkuester commented on app/src/main/java/com/sduduzog/slimlauncher/ui/options/CustomizeAppDrawerFragment.kt
> +        val subTitleText = getText(R.string.customize_app_drawer_fragment_auto_theme_wallpaper_subtext_no_default_launcher)
I really like using the subtitle text to indicate why the option is not available.  That is super clean and fits with the rest of the app well!

2022-08-09 02:52 UTC, jkuester commented on app/src/main/res/values/strings.xml
> +    <string name="prefs_key_automatic_wallpaper_shown" translatable="false">dialog_shown</string>
```suggestion
```
I don't think this is being used.

2022-08-09 02:52 UTC, jkuester commented on app/src/main/res/values/strings.xml
> +    <string name="ask_automatic_wallpaper_never">Never ask again</string>
Does this get pulled in somehow by the Android permissions system, or is it not actually getting used anywhere?

2022-08-09 21:14 UTC, hayribakici commented on app/src/main/java/com/sduduzog/slimlauncher/MainActivity.kt
> +        return unlauncherDataSource
That makes sense. So that means, that the `UnlaucherDataSource` is tightly bound to the `lifecycleScope` of the `MainActivity`. I wonder, if it is possible to provide the `UnlauncherDataSource` with a `@Provides` method, so that we could just inject it wherever we need to.

2022-08-09 21:16 UTC, hayribakici commented on app/src/main/java/com/sduduzog/slimlauncher/MainActivity.kt
> +            if (!it.setThemeWallpaper && getUserSelectedThemeRes() == resid) {
Yes, this additional `&& getUserSelectedThemeRes() == resid` is a super edge case: Since the user can opt-out setting the device wallpaper in the settings at any time, this extra condition prevents that setting the same wallpaper over and over again.

2022-08-09 21:21 UTC, hayribakici commented on app/src/main/java/com/sduduzog/slimlauncher/MainActivity.kt
> +    @Throws(IOException::class)
I thougth, I'd spare the extra `try-catch`, since since this method is only called in an `Dispatchers.IO`-thread, and nothing would happen anyway when it fails. But I can wrap a `try-catch`-block, if you think it's cleaner :)

2022-08-09 21:22 UTC, hayribakici commented on app/src/main/res/values/strings.xml
> +    <string name="ask_automatic_wallpaper_never">Never ask again</string>
No, not really. The `SET_WALLPAPER` permission, does not even appear in the general app settings. This string will be removed.

2022-08-10 21:49 UTC, hayribakici commented on app/src/main/java/com/sduduzog/slimlauncher/MainActivity.kt
> +        return unlauncherDataSource
I was able to provide a Hilt-Module for the `UnlauncherDataSource`:

```kotlin
@Module
@InstallIn(ActivityComponent::class)
object MainActivityModule {

    @Provides
    fun provideLifecycleCoroutineScope(activity: Activity): LifecycleCoroutineScope =
        (activity as ComponentActivity).lifecycleScope

    @Provides
    @ActivityScoped
    fun providesUnlauncherDataSource(activity: Activity, lifecycleCoroutineScope: LifecycleCoroutineScope) =
        UnlauncherDataSource(activity, lifecycleCoroutineScope)
}
```

and `@Inject` it in the `MainActivity`. Unfortunately I wasn't able to make it work, since the injected `unlauncherDataSource` instance is injected *after* `onCreate()`. And it is used in `onApplyTheme()` which is called *before* `onCreate()`. Do you have an idea on how to solve this?

2022-09-04 03:16 UTC, jkuester commented on app/src/main/java/com/sduduzog/slimlauncher/MainActivity.kt
> +        return unlauncherDataSource
Okay so after wasting a bunch of hours going down probably the same rabbit hole that you did, I have reached the same conclusion... :man_facepalming: I don't see a workable way to leverage injected dependencies from the `onApplyThemeResource` method. 

That being said, I really like the general idea of injecting the UnlauncherDataSource (instead of just sticking it in BaseFragment) and your module was pretty much the missing link in my brain that I needed to make that happen!  Let's not worry about it in this PR, but I definitely want to do a minor refactor to leverage that code.

Additionally, I realized that my concerns about multiple `UnlauncherDataSource` instances were totally unfounded since they will still be referencing the same DataStore entities under the hood. For good measure, I did some testing and was able to satisfy myself that everything remains consistent.  So, I am good with leaving things how we have it here now.

2022-09-04 03:17 UTC, merged