Add option to hide clock
jkuester/unlauncher pull request #146
Opened 2023-08-10 00:13 UTC by CubeOfCheese

Addresses #81 

Adds toggle control in options menu to display/hide the clock and date.

I am pretty new to Android development so all suggestions and advice are welcome.

![Screenshot_20230809_170911_Unlauncher](https://github.com/jkuester/unlauncher/assets/16740469/4abc1aff-dbaf-4a51-a3f0-675f041a523c)
![Screenshot_20230809_170918_Unlauncher](https://github.com/jkuester/unlauncher/assets/16740469/22a0adb4-5e6e-4340-b2fa-eb1217323068)
![Screenshot_20230809_170927_Unlauncher](https://github.com/jkuester/unlauncher/assets/16740469/e2238a43-2bce-4a16-8366-2333e11cee1a)
![Screenshot_20230809_170921_Unlauncher](https://github.com/jkuester/unlauncher/assets/16740469/4a4208cd-18e5-46a1-93dc-3fa7c7f7091c)

2023-08-10 08:38 UTC, hayribakici requested changes
Good job, please consider the review comments.

2023-08-10 08:38 UTC, hayribakici commented on app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt
> +            home_fragment_time.text = ""
Instead of setting the clock and date to an empty string, consider using visibility. In your case it would be 

```kotlin
home_fragment_time.visibility = View.INVISIBLE
home_fragmen_date.visibility = View.INVISIBLE
```

and analogously with `View.VISIBLE `when the time and date shold be displayed.

2023-08-10 08:38 UTC, hayribakici commented on app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt
> +            home_fragment_time.setOnClickListener {
When setting to `INVISIBLE` (see below), you don't need to check for `isClockDisplayed`, since the time and date are not visible and therefore the users are unable to interact with it (e.g. clicking on it). You can therefore remove the condition.

2023-08-10 08:38 UTC, hayribakici commented on app/src/main/java/com/sduduzog/slimlauncher/ui/options/OptionsFragment.kt
> +            val settings = requireContext().getSharedPreferences(getString(R.string.prefs_settings), MODE_PRIVATE)
You already have an instance of `settings` in line 66. You don't need it here anymore.

2023-08-10 20:54 UTC, CubeOfCheese commented on app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt
> +            home_fragment_time.text = ""
I did try this but it didn't seem to work. I will try to investigate further. I agree visibility is the ideal way to handle this.

2023-08-10 21:15 UTC, CubeOfCheese commented on app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt
> +            home_fragment_time.text = ""
Even if I set the visisbility to invisible directly in the xml, the clock still displays. So I'm thinking something else is interfering

2023-08-11 00:22 UTC, CubeOfCheese commented
Oh also I do not have translations in the strings.xml files. How would I go about doing that?

2023-08-11 10:16 UTC, hayribakici commented
@CubeOfCheese I wouldn't worry about it, right now :).

2023-08-11 10:19 UTC, hayribakici commented
@CubeOfCheese as for future pull requests (in any repository), you can resize your screenshots  (eg. to 300 px)  with the `img` tag like this:

```html
<img src="<your url here>" height="300px" />
```

2023-09-17 15:17 UTC, hayribakici commented on app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt
> +            home_fragment_time.text = ""
@CubeOfCheese Any luck with this issue?

2023-11-09 08:24 UTC, khwolf commented on app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt
> +            home_fragment_time.text = ""
I tried to set the `visibility` and the `alpha` value as well but it gets reset somehow. Did not find out where exactly.

What works is to set the height to zero:
```
home_fragment_time.height=0
home_fragment_date.height=0
```

2023-12-21 21:27 UTC, TobiTenno requested changes
@CubeOfCheese these look awesome. please revise based on some of the other review comments (like duplicate vals), and i'll get this another review shortly!

2023-12-29 21:42 UTC, closed without merging