Remove focus from search field on app launch
jkuester/unlauncher pull request #40
Opened 2021-03-08 16:43 UTC by edaigle

Bringing up the app drawer gives focus to the search field. This focus is never removed when we launch an app,
causing the keyboard to come up when we return to the main launcher view as described in #38.

Added a call to clearFocus() on the search field in onAppClicked(), removing the focus from the search field
and allowing us to return to the launcher without opening the keyboard as expected.

Closes #38

2021-03-08 16:46 UTC, edaigle commented
@jkuester to continue our discussion from earlier: this fixes the issue of the keyboard coming back up on pressing home, but doesn't fix a related issue where the keyboard stays up if we swipe back up from the app drawer after using the search field. I decided this was separate enough that it would be better to fix in a different MR, but just let me know if you'd rather I keep working and add it to this one.

2021-03-10 02:57 UTC, jkuester requested changes

2021-03-10 02:57 UTC, jkuester commented on app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt
> +        app_drawer_edit_text.clearFocus() // dismiss the on-screen keyboard
```suggestion
        app_drawer_edit_text.clearFocus() // dismiss the on-screen keyboard
        app_drawer_edit_text.clearComposingText()
```

Seems like we should also clear out any text that was entered (so the user does not have to delete it for the next search).

2021-03-10 14:11 UTC, jkuester approved these changes

2021-03-10 14:12 UTC, merged