Add french translation
jkuester/unlauncher pull request #46
Opened 2021-03-25 16:11 UTC by BoboTiG

This is a downstream patch of https://github.com/sduduzog/slim-launcher/commit/4d08abb7da4c08b30083f6877a42fc2a905ea830.

2021-03-26 10:39 UTC, BoboTiG commented
Should I fix "AAPT: error: unescaped apostrophe in string" errors?

2021-03-30 01:41 UTC, jkuester requested changes
Thank you for the translation!

Can you try adding these slashes I have suggested into the file?  I think the translation will technically work the way you have entered it, but some frameworks can get confused by those apostrophes (since in a lot of programming languages that represents the beginning/end of the text) and so the best-practice is to resolve the error.  The `\` character I am suggesting is known as an "escape character" which means it is just there to identify to the code that the following character (in this case the apostrophe) should be interpreted as plain text and not as indicating the beginning/end of the entry.  I have tested this locally and verified that the `\` escape character is not actually displayed to the user when running Unlauncher with the French locale.

2021-03-30 01:41 UTC, jkuester commented on app/src/main/res/values-fr/strings.xml
> +    <string name="choose_time_format_dialog_title">Format de l'heure</string>
```suggestion
    <string name="choose_time_format_dialog_title">Format de l\'heure</string>
```

2021-03-30 01:41 UTC, jkuester commented on app/src/main/res/values-fr/strings.xml
> +    <string name="options_fragment_about_slim">À propos d'Unlauncher</string>
```suggestion
    <string name="options_fragment_about_slim">À propos d'\Unlauncher</string>
```

2021-03-30 01:41 UTC, jkuester commented on app/src/main/res/values-fr/strings.xml
> +    <string name="options_fragment_choose_time_format">Format de l'Heure</string>
```suggestion
    <string name="options_fragment_choose_time_format">Format de l\'Heure</string>
```

2021-04-03 16:19 UTC, jkuester approved these changes

2021-04-03 16:20 UTC, merged